Algoritmo "16. qual o maior"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Marcelo Dipp 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 31/03/2025
Var
numerointeiro1,numerointeiro2,numerointeiro3 = inteiro


Inicio
escreval("console.log('socorro')")
escreval("qual o maior")
escreval(" digite os 3 numeros")





Fimalgoritmo