Algoritmo "8"
Var
    num1, num2, num3, num4, media: real
Inicio
    escreval("Digite o primeiro número:")
    leia(num1)

    escreval("Digite o segundo número:")
    leia(num2)

    escreval("Digite o terceiro número:")
    leia(num3)

    escreval("Digite o quarto número:")
    leia(num4)

    media <- (num1 + num2 + num3 + num4) / 4

    escreval("A média aritmética é: ", media)
Fimalgoritmo
