Algoritmo "negocio louko"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor    : Marcelo Dipp
// Descrição    : Calcula a equação (x + 12) / 3
// Autor(a)     : Girelli
// Data atual   : 27/03/2025

Var
    x, resultado: real

Inicio
    escreva("Digite o valor que deseja usar: ")
    leia(x)

    resultado <- (x + 12) / 3

    escreva("Resultado: ", resultado)
Fimalgoritmo
