Algoritmo "semnome"
// Disciplina  :  [Linguagem e Lógica de Programação] 
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 31/03/2025
Var
// Seção de Declarações das variáveis 
x,y,z:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
leia(x,y)
  z<-x mod y
  escreval(z)

Fimalgoritmo